insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Heineken', 'Netherlands', 'Heineken International', 'Lager', 4.5, 5, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100);

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Coors Light', 'United States', 'Coors Brewing', 'Lager', 4.2, 5, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100  );

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Guinness', 'Ireland', 'Diageo', 'Stout', 4.2, 6, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100);

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Abbot Ale', 'England', 'Green King', 'Ale', 5, 6, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100  );

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Punk IPA', 'United States', 'Brewdog', 'IPA', 5.6, 6.5, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100);

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Doombar', 'England', 'Sharps Brewery', 'Ale', 4.3, 4.3, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100  );

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Hobgoblin', 'England', 'Refresh UK', 'Ale', 5.2, 5.2, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100);

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Peroni', 'Italy', 'Vigevano', 'Lager', 5.1, 5.1, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100  );

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Asahi', 'Japan', 'Asahi Group', 'Lager', 5, 8, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100);

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('Tsingtao', 'China', 'Tsingtao Brewery', 'Lager', 4.7, 10, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 100, 100  );

insert into beerStocked(name, country, brewer, type, abv, price, image, description, totalStock, availableStock)
values('San Miguel', 'Philippines', 'San Miguel Brewery', 'Lager', 5, 4.5, '/img/beer-template.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Maecenas volutpat blandit aliquam etiam. Scelerisque varius morbi enim nunc faucibus. Eu consequat ac felis donec. Non blandit massa enim nec dui nunc mattis enim ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. At risus viverra adipiscing at in tellus integer feugiat.', 0, 0);
