# Configuration file for CircleCI
version: 2
jobs:
  build:
    working_directory: ~/circleci-global-beer-shop
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      steps:

      - checkout

      - restore_cache:
          key: circleci-global-beer-shop-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-global-beer-shop-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/global-beer-shop-0.0.1-SNAPSHOT.jar
